[package]
name = "openai-structured-client"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["json"] }
schemars = "0.8.21"
serde = "1.0.216"
serde_json = "1.0.133"
tokio = { version = "1.39.3", features = ["full"] }
